### ISSUE TITLE
Allow for doctor/patient/admin to see their list of consults and filter by keyword

### ISSUE THREAD

**Issue by SuryaPugal** [tkomarlu/TeladocCapstone#3]
**As a Doctor and/or Patient I can search keywords over past transcriptions, view matched context and listen to consultation records only of my past consultations so that I can review past consult records and find key information.**

**As an Admin I can search keywords over past transcriptions, view matched context and listen to consultation records of all past consultations so that I can review past consult records and find key information for the audit purpose.**

- [ ] I should be able to access and click on the dashboard to enable relevant filters (i.e: by patient, by date, etc.)

- [ ] I should be able to click on a certain consult within said list and get redirected to another page pertaining to the consult in question.

- [ ] I should be able to see if a consult was flagged for some particular reason (for doctor/admin).

**Comment by sairam9346** [comment]
no
